@startuml
interface org.proorm.executor.IStatementExecutor {
~ List<Long> executeUpdate(IQueryTarget,String,List<List<Object>>,String)
~ List<Map<String,Object>> executeSelect(IQueryTarget,String,List<Object>,Map<String,Class<?>>)
}
interface org.proorm.IDatabaseConfig {
~ DataSource getDataSource()
~ IDatabaseConfig dataSource(DataSource)
~ ISQLDialect getDialect()
~ IDatabaseConfig dialect(ISQLDialect)
~ IORMappingProvider getORMappingProvider()
~ IDatabaseConfig ORMappingProvider(IORMappingProvider)
~ IJDBCTypeMapper getJDBCTypeMapper()
~ IDatabaseConfig JDBCTypeMapper(IJDBCTypeMapper)
~ IStatementExecutor getStatementExecutor()
~ IDatabaseConfig statementExecutor(IStatementExecutor)
~ IDatabaseConfig build()
}
class org.proorm.attributeconverter.AttributeConverterUtils {
+ {static} Class<?> getConverterDatabaseType(AttributeConverter)
}
class org.proorm.Database {
- IDatabaseConfig config
+ IDatabaseConfig getConfig()
+ Connection getConnection()
+ void releaseConnection(Connection)
}
interface org.proorm.crud.IInsertQuery {
~ IORMInsertQuery<T> insert(Class<T>)
~ void insert(T)
~ void insert(Collection<T>)
~ IGenericInsertQuery insert(String)
}
interface org.proorm.mapping.provider.IORMappingProvider {
~ ORMapping getORMapping(Class<?>)
}
class org.proorm.result.object.ObjectResult {
- Class<T> clazz
# T castRow(Map<String,Object>)
# Object canonicalValue(Class<?>)
# ORMapping getMapping()
# Map<String,Class<?>> typeMappings()
}
abstract class org.proorm.executor.AbstractStatementExecutor {
+ List<Map<String,Object>> executeSelect(IQueryTarget,String,List<Object>,Map<String,Class<?>>)
# void setParameters(IQueryTarget,PreparedStatement,List<Object>)
# Object getObject(IQueryTarget,ResultSet,ResultSetMetaData,int,Class<?>)
# void setObject(IQueryTarget,PreparedStatement,int,Object)
# int getGeneratedColumnIndex(IQueryTarget,ResultSet,String)
}
interface org.proorm.crud.ISelectQuery {
~ IORMSelectQuery<T> select(Class<T>)
~ T select(Class<T>,Object)
~ IGenericSelectQuery select(String,Object)
}
class org.proorm.mapping.ColumnMapping {
- PropertyDescriptor propertyDescriptor
- String columnDefinition
- boolean isId
- boolean insertable
- Integer length
- String column
- boolean nullable
- Integer precision
- Integer scale
- boolean updatable
- boolean generated
- AttributeConverter converter
+ PropertyDescriptor getPropertyDescriptor()
+ void setPropertyDescriptor(PropertyDescriptor)
+ String getColumnDefinition()
+ void setColumnDefinition(String)
+ boolean isInsertable()
+ void setInsertable(boolean)
+ Integer getLength()
+ void setLength(Integer)
+ String getName()
+ void setColumn(String)
+ boolean isNullable()
+ void setNullable(boolean)
+ Integer getPrecision()
+ void setPrecision(Integer)
+ Integer getScale()
+ void setScale(Integer)
+ boolean isUpdatable()
+ void setUpdatable(boolean)
+ boolean isId()
+ void setId(boolean)
+ boolean isGenerated()
+ void setGenerated(boolean)
+ AttributeConverter<?,?> getConverter()
+ void setConverter(AttributeConverter<?,?>)
+ Object getValue(Object)
+ void writeProperty(Object,Object)
- {static} Field getField(Class,String)
}
abstract class org.proorm.result.AbstractResult {
- IQueryTarget queryTarget
- String sql
- List<Object> params
+ T one()
+ T first()
+ List<T> list()
# IQueryTarget getQueryTarget()
# {abstract}T castRow(Map<String,Object>)
# {abstract}Map<String,Class<?>> typeMappings()
}
class org.proorm.query.generic.GenericRawQuery {
- String sql
- List<Object> params
+ IGenericRawQuery sql(String,Object)
+ void execute()
}
class org.proorm.query.generic.GenericInsertQuery {
- String schema
- String table
- String generatedId
- List<Map<String,Object>> values
+ IGenericInsertQuery table(String)
+ IGenericInsertQuery generatedId(String)
+ IGenericInsertQuery addOne(Map<String,Object>)
+ IGenericInsertQuery addMany(List<Map<String,Object>>)
+ void execute()
}
class org.proorm.result.map.MapResult {
- Class<V> type
# Map<String,V> castRow(Map<String,Object>)
# Map<String,Class<?>> typeMappings()
}
interface org.proorm.crud.IUpdateQuery {
~ IORMUpdateQuery<T> update(Class<T>)
~ void update(T)
~ void update(Collection<T>)
~ IGenericUpdateQuery update(String)
}
interface org.proorm.query.orm.IORMQuery {
~ IORMQuery<T> forClass(Class<T>)
}
interface org.proorm.query.orm.IORMDeleteQuery {
~ IORMDeleteQuery<T> forClass(Class<T>)
~ IORMDeleteQuery<T> id(Object)
~ IORMDeleteQuery<T> addOne(T)
~ IORMDeleteQuery<T> addMany(Collection<T>)
~ IORMDeleteQuery<T> where(String,Object)
~ void execute()
}
interface org.proorm.query.generic.IGenericUpdateQuery {
~ IGenericUpdateQuery schema(String)
~ IGenericUpdateQuery table(String)
~ IGenericUpdateQuery idColumn(String)
~ IGenericUpdateQuery idColumns(String)
~ IGenericUpdateQuery addOne(Map<String,Object>)
~ IGenericUpdateQuery addMany(List<Map<String,Object>>)
~ void execute()
}
interface org.proorm.dialect.ISQLDialect {
~ String sqlForDelete(String,List<String>)
~ String sqlForDeleteWhere(String,String)
~ String sqlForInsert(String,List<String>)
~ String sqlForUpdate(String,List<String>,List<String>)
~ String sqlForSelect(String,Integer,Integer)
~ String sqlForSelectWhere(List<String>,String,String)
~ String sqlForSelect(List<String>,String,String,String,String)
~ String sqlForCreateTable(ORMapping)
~ String sqlForDropTable(ORMapping)
~ SetNullParameterMethod getSetNullParameterMethod()
}
class org.proorm.attributeconverter.EnumOrdinalAttributeConverter {
- Map<Integer,T> lookup
+ Integer convertToDatabaseColumn(T)
+ T convertToEntityAttribute(Integer)
}
class org.proorm.query.orm.ORMDropTableQuery {
+ IORMDropTableQuery<T> forClass(Class<T>)
+ void execute()
}
interface org.proorm.query.generic.IGenericInsertQuery {
~ IGenericInsertQuery table(String)
~ IGenericInsertQuery generatedId(String)
~ IGenericInsertQuery addOne(Map<String,Object>)
~ IGenericInsertQuery addMany(List<Map<String,Object>>)
~ void execute()
}
class org.proorm.query.orm.ORMCreateTableQuery {
+ IORMCreateTableQuery<T> forClass(Class<T>)
+ void execute()
}
interface org.proorm.query.generic.IGenericSelectQuery {
~ IGenericSelectQuery sql(String,Object)
~ IMapResult<Object> toMap()
~ IObjectResult<T> toObject(Class<T>)
}
interface org.proorm.result.object.IObjectResult {
}
interface org.proorm.query.IQuery {
~ void setQueryTarget(IQueryTarget)
~ IQueryTarget getQueryTarget()
}
abstract class org.proorm.QueryTargetFactory {
+ IORMSelectQuery<T> select(Class<T>)
+ T select(Class<T>,Object)
+ IGenericSelectQuery select(String,Object)
+ IORMInsertQuery<T> insert(Class<T>)
+ void insert(T)
+ void insert(Collection<T>)
+ IGenericInsertQuery insert(String)
+ IORMUpdateQuery<T> update(Class<T>)
+ void update(T)
+ void update(Collection<T>)
+ IGenericUpdateQuery update(String)
+ IORMDeleteQuery<T> delete(Class<T>)
+ void delete(Class<T>,Object)
+ void delete(T)
+ void delete(Collection<T>)
+ IGenericDeleteQuery delete(String)
+ void createTable(Class<T>)
+ void dropTable(Class<T>)
+ void sql(String,Object)
+ List<Long> executeUpdate(String,List<List<Object>>,String)
+ List<Map<String,Object>> executeQuery(String,List<Object>,Map<String,Class<?>>)
}
class org.proorm.attributeconverter.EnumNameAttributeConverter {
- Class<T> enumClass
+ String convertToDatabaseColumn(T)
+ T convertToEntityAttribute(String)
}
class org.proorm.query.orm.ORMUpdateQuery {
- List<T> objs
+ IORMUpdateQuery<T> forClass(Class<T>)
+ ORMUpdateQuery<T> addOne(T)
+ ORMUpdateQuery<T> addMany(Collection<T>)
+ void execute()
}
interface org.proorm.query.generic.IGenericQuery {
}
class org.proorm.dialect.PostgreSQLDialect {
# String sqlForAutoIncrement()
# String sqlForColumnType(Class<?>,Integer,Integer,Integer,boolean)
}
class org.proorm.mapping.provider.JPAORMFactory {
# ORMapping createORMapping(Class<?>)
}
interface org.proorm.IDatabase {
}
interface org.proorm.IQueryTarget {
~ Connection getConnection()
~ void releaseConnection(Connection)
~ IDatabaseConfig getConfig()
}
class org.proorm.query.orm.ORMDeleteQuery {
- List<List<Object>> ids
- String where
- List<Object> params
+ IORMDeleteQuery<T> forClass(Class<T>)
+ IORMDeleteQuery<T> id(Object)
+ IORMDeleteQuery<T> addOne(T)
+ IORMDeleteQuery<T> addMany(Collection<T>)
+ IORMDeleteQuery<T> where(String,Object)
+ void execute()
}
abstract class org.proorm.query.generic.AbstractGenericQuery {
}
class org.proorm.query.AbstractQuery {
- IQueryTarget target
+ void setQueryTarget(IQueryTarget)
+ IQueryTarget getQueryTarget()
}
class org.proorm.query.generic.GenericDeleteQuery {
- String schema
- String table
- List<String> idColumns
- List<List<Object>> ids
- String where
- List<Object> params
+ IGenericDeleteQuery schema(String)
+ IGenericDeleteQuery table(String)
+ IGenericDeleteQuery idColumn(String)
+ IGenericDeleteQuery idColumns(String)
+ IGenericDeleteQuery addOne(Object)
+ IGenericDeleteQuery addMany(List<Object>)
+ IGenericDeleteQuery where(String,Object)
+ void execute()
}
class org.proorm.exception.DBException {
}
class org.proorm.exception.UnexpectedNumberOfItemsException {
- int actual
+ int getActual()
}
class org.proorm.query.orm.ORMInsertQuery {
- List<T> columnTypes
+ IORMInsertQuery<T> forClass(Class<T>)
+ ORMInsertQuery<T> addOne(T)
+ ORMInsertQuery<T> addMany(Collection<T>)
+ void execute()
}
interface org.proorm.query.generic.IGenericRawQuery {
~ IGenericRawQuery sql(String,Object)
~ void execute()
}
enum org.proorm.dialect.SetNullParameterMethod {
+  SETNULL
+  SETOBJECT
}
class org.proorm.DatabaseConfig {
- DataSource dataSource
- ISQLDialect dialect
- IORMappingProvider mappingProvider
- IJDBCTypeMapper typeMapper
- IStatementExecutor executor
+ DataSource getDataSource()
+ IDatabaseConfig dataSource(DataSource)
+ ISQLDialect getDialect()
+ IDatabaseConfig dialect(ISQLDialect)
+ IORMappingProvider getORMappingProvider()
+ IDatabaseConfig ORMappingProvider(IORMappingProvider)
+ IJDBCTypeMapper getJDBCTypeMapper()
+ IDatabaseConfig JDBCTypeMapper(IJDBCTypeMapper)
+ IStatementExecutor getStatementExecutor()
+ IDatabaseConfig statementExecutor(IStatementExecutor)
+ IDatabaseConfig build()
}
class org.proorm.mapping.ORMapping {
- Class<?> clazz
- String schema
- String tableName
- List<ColumnMapping> columnMappings
- CaseInsensitiveMap<ColumnMapping> columnMappingsIndexedByProperty
- CaseInsensitiveMap<ColumnMapping> columnMappingsIndexedByColumn
- List<ColumnMapping> idColumnMappings
- Boolean hasId
+ Class<?> getClazz()
+ void setClazz(Class<?>)
+ String getSchema()
+ void setSchema(String)
+ String getTableName()
+ void setTableName(String)
+ List<ColumnMapping> getColumnMappings()
+ void setColumnMappings(List<ColumnMapping>)
+ ColumnMapping getColumnMappingByProperty(String)
# CaseInsensitiveMap<ColumnMapping> createColumnMappingsIndexedByProperty()
+ ColumnMapping getColumnMappingByColumn(String)
# CaseInsensitiveMap<ColumnMapping> createColumnMappingsIndexedByColumn()
+ List<ColumnMapping> getIdColumnMappings()
+ ColumnMapping getIdColumnMapping()
+ Boolean hasId()
}
class org.proorm.mapping.type.DefaultJDBCTypeMapper {
+ Class<?> getJavaType(int)
}
class org.proorm.query.orm.ORMSelectQuery {
- String where
- List<Object> params
- String groupBy
- String having
+ IORMSelectQuery<T> forClass(Class<T>)
+ IORMSelectQuery<T> where(String,Object)
+ IORMSelectQuery<T> groupBy(String,Object)
+ IORMSelectQuery<T> having(String,Object)
+ IORMSelectQuery<T> id(Object)
+ IORMSelectQuery<T> groupBy(String)
+ IORMSelectQuery<T> having(String)
+ T one()
+ T first()
+ List<T> list()
# IObjectResult<T> getResult()
# String buildSQL()
}
interface org.proorm.crud.IDeleteQuery {
~ IORMDeleteQuery<T> delete(Class<T>)
~ void delete(Class<T>,Object)
~ void delete(T)
~ void delete(Collection<T>)
~ IGenericDeleteQuery delete(String)
}
interface org.proorm.query.orm.IORMCreateTableQuery {
~ IORMCreateTableQuery<T> forClass(Class<T>)
~ void execute()
}
class org.proorm.executor.DefaultStatementExecutor {
+ List<Long> executeUpdate(IQueryTarget,String,List<List<Object>>,String)
}
interface org.proorm.query.orm.IORMUpdateQuery {
~ IORMUpdateQuery<T> forClass(Class<T>)
~ IORMUpdateQuery<T> addOne(T)
~ IORMUpdateQuery<T> addMany(Collection<T>)
~ void execute()
}
class org.proorm.query.generic.GenericSelectQuery {
- String sql
- List<Object> params
+ IGenericSelectQuery sql(String,Object)
+ IMapResult<Object> toMap()
+ IObjectResult<T> toObject(Class<T>)
# String getSQL()
}
abstract class org.proorm.mapping.provider.AbstractORMFactory {
- Map<Class<?>,ORMapping> mappings
+ ORMapping getORMapping(Class<?>)
# {abstract}ORMapping createORMapping(Class<?>)
}
interface org.proorm.result.map.IMapResult {
}
interface org.proorm.crud.ITableQuery {
~ void createTable(Class<T>)
~ void dropTable(Class<T>)
~ void sql(String,Object)
~ List<Long> executeUpdate(String,List<List<Object>>,String)
~ List<Map<String,Object>> executeQuery(String,List<Object>,Map<String,Class<?>>)
}
class org.proorm.query.generic.GenericUpdateQuery {
- String schema
- String table
- List<String> idColumns
- List<Map<String,Object>> values
+ IGenericUpdateQuery schema(String)
+ IGenericUpdateQuery table(String)
+ IGenericUpdateQuery idColumn(String)
+ IGenericUpdateQuery idColumns(String)
+ IGenericUpdateQuery addOne(Map<String,Object>)
+ IGenericUpdateQuery addMany(List<Map<String,Object>>)
+ void execute()
}
interface org.proorm.query.orm.IORMSelectQuery {
~ IORMSelectQuery<T> forClass(Class<T>)
~ IORMSelectQuery<T> where(String,Object)
~ IORMSelectQuery<T> groupBy(String,Object)
~ IORMSelectQuery<T> having(String,Object)
~ IORMSelectQuery<T> id(Object)
~ IORMSelectQuery<T> groupBy(String)
~ IORMSelectQuery<T> having(String)
}
interface org.proorm.query.orm.IORMDropTableQuery {
~ IORMDropTableQuery<T> forClass(Class<T>)
~ void execute()
}
class org.proorm.dialect.GenericSQLDialect {
+ String sqlForDelete(String,List<String>)
# String sqlForDeleteIdEscaped(String,List<String>)
+ String sqlForDeleteWhere(String,String)
# String sqlForDeleteWhereIdEscaped(String,String)
+ String sqlForInsert(String,List<String>)
# String sqlForInsertIdEscaped(String,List<String>)
+ String sqlForUpdate(String,List<String>,List<String>)
# String sqlForUpdateIdEscaped(String,List<String>,List<String>)
+ String sqlForSelect(String,Integer,Integer)
+ String sqlForSelectWhere(List<String>,String,String)
+ String sqlForSelect(List<String>,String,String,String,String)
# String sqlForSelectIdEscaped(List<String>,String,String)
# String sqlForSelectIdEscaped(List<String>,String,String,String,String)
+ String sqlForDropTable(ORMapping)
+ String sqlForCreateTable(ORMapping)
# String sqlForColumnDefinition(ColumnMapping)
# String sqlForColumnType(ColumnMapping)
# String sqlForColumnType(Class<?>,Integer,Integer,Integer,boolean)
# String sqlForAutoIncrement()
# String sqlForPrimaryKey(ORMapping,List<ColumnMapping>)
# List<String> questionMarks(int)
# List<String> identifiers(List<String>)
# String identifier(String,String)
# String schemaPrefix(String)
# String identifier(String,boolean)
# String identifier(String)
# String quoteIdentifier(String)
+ SetNullParameterMethod getSetNullParameterMethod()
}
interface org.proorm.result.IResult {
~ T one()
~ T first()
~ List<T> list()
}
class org.proorm.mapping.JPAORMapping {
# {static} Field getField(Class<?>,String)
}
abstract class org.proorm.query.orm.AbstractORMQuery {
- Class<T> clazz
+ IORMQuery<T> forClass(Class<T>)
# Class<T> getTargetClass()
# ORMapping getMapping()
}
class org.proorm.utils.RSUtils {
+ {static} Map<K,List<T>> group(List<T>,String)
+ {static} Map<K,T> index(List<T>,String)
+ {static} Set<K> distinct(List<T>,String)
- {static} IPropertyReader<T> getReader(Class<T>,String)
}
interface org.proorm.utils.RSUtils$IPropertyReader {
~ Object readProperty(T)
}
class org.proorm.utils.RSUtils$MapPropertyReader {
- String property
+ Object readProperty(Map)
}
class org.proorm.utils.RSUtils$ObjectPropertyReader {
- Method reader
+ Object readProperty(T)
}
abstract class org.proorm.attributeconverter.JsonAttributeConverter {
- JavaType javaType
- ObjectMapper mapper
- ObjectReader reader
- ObjectWriter writer
+ String convertToDatabaseColumn(T)
+ T convertToEntityAttribute(String)
# ObjectMapper getMapper()
# ObjectWriter getWriter()
# ObjectReader getReader()
# JavaType getJavaType()
}
interface org.proorm.query.generic.IGenericDeleteQuery {
~ IGenericDeleteQuery schema(String)
~ IGenericDeleteQuery table(String)
~ IGenericDeleteQuery idColumn(String)
~ IGenericDeleteQuery idColumns(String)
~ IGenericDeleteQuery addOne(Object)
~ IGenericDeleteQuery addMany(List<Object>)
~ IGenericDeleteQuery where(String,Object)
~ void execute()
}
interface org.proorm.query.orm.IORMInsertQuery {
~ IORMInsertQuery<T> forClass(Class<T>)
~ IORMInsertQuery<T> addOne(T)
~ IORMInsertQuery<T> addMany(Collection<T>)
~ void execute()
}
class org.proorm.utils.CaseInsensitiveMap {
+ void putAll(Map<? extends String,? extends T>)
+ T put(String,T)
+ T get(Object)
}
interface org.proorm.mapping.type.IJDBCTypeMapper {
~ Class<?> getJavaType(int)
}


org.proorm.IDatabase <|.. org.proorm.Database
org.proorm.QueryTargetFactory <|-- org.proorm.Database
org.proorm.result.object.IObjectResult <|.. org.proorm.result.object.ObjectResult
org.proorm.result.AbstractResult <|-- org.proorm.result.object.ObjectResult
org.proorm.executor.IStatementExecutor <|.. org.proorm.executor.AbstractStatementExecutor
org.proorm.result.IResult <|.. org.proorm.result.AbstractResult
org.proorm.query.generic.IGenericRawQuery <|.. org.proorm.query.generic.GenericRawQuery
org.proorm.query.AbstractQuery <|-- org.proorm.query.generic.GenericRawQuery
org.proorm.query.generic.IGenericInsertQuery <|.. org.proorm.query.generic.GenericInsertQuery
org.proorm.query.AbstractQuery <|-- org.proorm.query.generic.GenericInsertQuery
org.proorm.result.map.IMapResult <|.. org.proorm.result.map.MapResult
org.proorm.result.AbstractResult <|-- org.proorm.result.map.MapResult
org.proorm.query.IQuery <|-- org.proorm.query.orm.IORMQuery
org.proorm.query.orm.IORMQuery <|-- org.proorm.query.orm.IORMDeleteQuery
org.proorm.query.generic.IGenericQuery <|-- org.proorm.query.generic.IGenericUpdateQuery
javax.persistence.AttributeConverter <|.. org.proorm.attributeconverter.EnumOrdinalAttributeConverter
org.proorm.query.orm.IORMDropTableQuery <|.. org.proorm.query.orm.ORMDropTableQuery
org.proorm.query.orm.AbstractORMQuery <|-- org.proorm.query.orm.ORMDropTableQuery
org.proorm.query.generic.IGenericQuery <|-- org.proorm.query.generic.IGenericInsertQuery
org.proorm.query.orm.IORMCreateTableQuery <|.. org.proorm.query.orm.ORMCreateTableQuery
org.proorm.query.orm.AbstractORMQuery <|-- org.proorm.query.orm.ORMCreateTableQuery
org.proorm.query.generic.IGenericQuery <|-- org.proorm.query.generic.IGenericSelectQuery
org.proorm.result.IResult <|-- org.proorm.result.object.IObjectResult
org.proorm.IQueryTarget <|.. org.proorm.QueryTargetFactory
javax.persistence.AttributeConverter <|.. org.proorm.attributeconverter.EnumNameAttributeConverter
org.proorm.query.orm.IORMUpdateQuery <|.. org.proorm.query.orm.ORMUpdateQuery
org.proorm.query.orm.AbstractORMQuery <|-- org.proorm.query.orm.ORMUpdateQuery
org.proorm.query.IQuery <|-- org.proorm.query.generic.IGenericQuery
org.proorm.dialect.GenericSQLDialect <|-- org.proorm.dialect.PostgreSQLDialect
org.proorm.mapping.provider.AbstractORMFactory <|-- org.proorm.mapping.provider.JPAORMFactory
org.proorm.IQueryTarget <|-- org.proorm.IDatabase
org.proorm.ISelectQuery <|-- org.proorm.IQueryTarget
org.proorm.IInsertQuery <|-- org.proorm.IQueryTarget
org.proorm.IUpdateQuery <|-- org.proorm.IQueryTarget
org.proorm.ITableQuery <|-- org.proorm.IQueryTarget
org.proorm.IDeleteQuery <|-- org.proorm.IQueryTarget
org.proorm.query.orm.IORMDeleteQuery <|.. org.proorm.query.orm.ORMDeleteQuery
org.proorm.query.orm.AbstractORMQuery <|-- org.proorm.query.orm.ORMDeleteQuery
org.proorm.query.generic.IGenericQuery <|.. org.proorm.query.generic.AbstractGenericQuery
org.proorm.query.AbstractQuery <|-- org.proorm.query.generic.AbstractGenericQuery
org.proorm.query.IQuery <|.. org.proorm.query.AbstractQuery
org.proorm.query.generic.IGenericDeleteQuery <|.. org.proorm.query.generic.GenericDeleteQuery
org.proorm.query.generic.AbstractGenericQuery <|-- org.proorm.query.generic.GenericDeleteQuery
org.proorm.exception.RuntimeException <|-- org.proorm.exception.DBException
org.proorm.exception.Exception <|-- org.proorm.exception.UnexpectedNumberOfItemsException
org.proorm.query.orm.IORMInsertQuery <|.. org.proorm.query.orm.ORMInsertQuery
org.proorm.query.orm.AbstractORMQuery <|-- org.proorm.query.orm.ORMInsertQuery
org.proorm.query.generic.IGenericQuery <|-- org.proorm.query.generic.IGenericRawQuery
org.proorm.IDatabaseConfig <|.. org.proorm.DatabaseConfig
org.proorm.mapping.type.IJDBCTypeMapper <|.. org.proorm.mapping.type.DefaultJDBCTypeMapper
org.proorm.query.orm.IORMSelectQuery <|.. org.proorm.query.orm.ORMSelectQuery
org.proorm.query.orm.AbstractORMQuery <|-- org.proorm.query.orm.ORMSelectQuery
org.proorm.query.orm.IORMQuery <|-- org.proorm.query.orm.IORMCreateTableQuery
org.proorm.executor.AbstractStatementExecutor <|-- org.proorm.executor.DefaultStatementExecutor
org.proorm.query.orm.IORMQuery <|-- org.proorm.query.orm.IORMUpdateQuery
org.proorm.query.generic.IGenericSelectQuery <|.. org.proorm.query.generic.GenericSelectQuery
org.proorm.query.AbstractQuery <|-- org.proorm.query.generic.GenericSelectQuery
org.proorm.mapping.provider.IORMappingProvider <|.. org.proorm.mapping.provider.AbstractORMFactory
org.proorm.result.IResult <|-- org.proorm.result.map.IMapResult
org.proorm.query.generic.IGenericUpdateQuery <|.. org.proorm.query.generic.GenericUpdateQuery
org.proorm.query.AbstractQuery <|-- org.proorm.query.generic.GenericUpdateQuery
org.proorm.query.orm.IORMQuery <|-- org.proorm.query.orm.IORMSelectQuery
org.proorm.result.object.IObjectResult <|-- org.proorm.query.orm.IORMSelectQuery
org.proorm.query.orm.IORMQuery <|-- org.proorm.query.orm.IORMDropTableQuery
org.proorm.dialect.ISQLDialect <|.. org.proorm.dialect.GenericSQLDialect
org.proorm.mapping.ORMapping <|-- org.proorm.mapping.JPAORMapping
org.proorm.query.orm.IORMQuery <|.. org.proorm.query.orm.AbstractORMQuery
org.proorm.query.AbstractQuery <|-- org.proorm.query.orm.AbstractORMQuery
org.proorm.utils.RSUtils +.. org.proorm.utils.RSUtils$IPropertyReader
org.proorm.utils.RSUtils +.. org.proorm.utils.RSUtils$MapPropertyReader
org.proorm.utils.IPropertyReader <|.. org.proorm.utils.RSUtils$MapPropertyReader
org.proorm.utils.RSUtils +.. org.proorm.utils.RSUtils$ObjectPropertyReader
org.proorm.utils.IPropertyReader <|.. org.proorm.utils.RSUtils$ObjectPropertyReader
javax.persistence.AttributeConverter <|.. org.proorm.attributeconverter.JsonAttributeConverter
org.proorm.query.generic.IGenericQuery <|-- org.proorm.query.generic.IGenericDeleteQuery
org.proorm.query.orm.IORMQuery <|-- org.proorm.query.orm.IORMInsertQuery
java.util.LinkedHashMap <|-- org.proorm.utils.CaseInsensitiveMap
@enduml